version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - Dockerfile
    - 'dist/**/*'
    - package.json
    - package-lock.json
    - tsconfig.json
